### ISSUE TITLE
Raise exception on wiringPi failure

### ISSUE THREAD

**Issue by elegantandrogyne** [Gadgetoid/WiringPi2-Python#33]
Test case:

`import wiringpi2 as wiringpi`
`wiringpi.mcp23017Setup(65, 0x20)`

Works on a Raspberry with mcp23017, crashes to shell otherwise.
wiringPi output on Raspberry without mcp23017:

`Unable to open I2C device: No such file or directory`

wiringPi output on non-Raspberry (e.g. Lenovo T61p with Debian stretch):

`piBoardRev: Unable to determine board revision from /proc/cpuinfo`
` -> No "Hardware" line`
` ->  You may want to check:`
` ->  http://www.raspberrypi.org/phpBB3/viewtopic.php?p=184410#p184410`

Is it possible to raise an exception whenever wiringPi exits with EXIT_FAILURE status (with whatever it prints to stderr in the exception message) instead of crashing?
(current version of wiringPi has 22 places where it happens: https://git.drogon.net/?p=wiringPi&a=search&h=HEAD&st=grep&s=EXIT_FAILURE )

**Comment by Gadgetoid** [comment]
Possibly possible. However I've had precious little time to maintain this code and if I'm honest I certainly didn't understand Python/C bindings when I put it together, and I've not spent much time on them since then.

I'm still watching this project, however, and plan some housekeeping when I get the opportunity.
